pipeline {
    agent any
    
    environment {
        // Enforce PowerShell Core as the default shell step execution
        JENKINS_POWERSHELL_COMMAND = 'pwsh'
        // SET FO BUILD ENVIRONMENT VARIABLES
        GOOS="windows"
        GOARCH="amd64"
        CGO_ENABLED="0"
    }

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Build Go Binary') {
            steps {
                powershell '''
                    Write-Host "BEFORE"

                    Write-Host "Env:GOOS        =$($env:GOOS)"
                    Write-Host "Env:GOARCH      =$($env:GOARCH)"
                    Write-Host "Env:CGO_ENABLED =$($env:CGO_ENABLED)"

                    # Go the module directory
                    cd ./example/helloworld

                    Write-Host "AFTER"
                    Write-Host "Env:GOOS        =$($env:GOOS)"
                    Write-Host "Env:GOARCH      =$($env:GOARCH)"
                    Write-Host "Env:CGO_ENABLED =$($env:CGO_ENABLED)"
                    
                    # Compile the binary
                    go build -o helloworld.exe
                    
                '''
            }
        }

    }

    post {
        success {
            // Archive the zip file in Jenkins for record-keeping
            archiveArtifacts artifacts: 'helloworld.exe', fingerprint: true
        }
    }
}