pipeline {
    agent any
    
    environment {
        // Enforce PowerShell Core as the default shell step execution
        JENKINS_POWERSHELL_COMMAND = 'pwsh'
        // SET FO BUILD ENVIRONMENT VARIABLES
        GOOS="windows"
        GOARCH="amd64"
        CGO_ENABLED="0"
    }

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Build Go Binary') {
            steps {
                printGoEnvironmentVariables('BEFORE BUILD')

                def changeLogSets = currentBuild.changeSets
                for (int i = 0; i < changeLogSets.size(); i++) {
                    def entries = changeLogSets[i].items
                    for (int j = 0; j < entries.size(); j++) {
                        for (path in entries[j].affectedPaths) {
                            echo ${path}
                        }
                    }
                }

                powershell '''
                    # 1. Initialize the temporary workspace
                    go work init
                    go work use ./example/module1
                    go work use ./example/helloworld

                    # 2. Resync the workspace metadata with your checked-in vendor folder
                    go work vendor

                    # 3. Compile by explicitly reusing the synchronized vendor directory
                    go build -mod=vendor -o ./example/helloworld/helloworld.exe ./example/helloworld

                    # 4. Cleanup workspace files, leaving your vendor folder untouched
                    Remove-Item go.work, go.work.sum -ErrorAction SilentlyContinue
                '''
            }
        }

    }

    post {
        success {
            // Archive the zip file in Jenkins for record-keeping
            //archiveArtifacts artifacts: 'helloworld.exe', fingerprint: true
            archiveArtifacts artifacts: 'example/helloworld/helloworld.exe', fingerprint: true
        }
    }


}

def printGoEnvironmentVariables(String comment) {
    powershell """
        Write-Host "Comment         = ${comment}"
        Write-Host "Stage           = ${env.STAGE_NAME}"
        
        # Single quotes protect these from Groovy manipulation completely
        Write-Host 'Env:GOOS        =' \$env:GOOS
        Write-Host 'Env:GOARCH      =' \$env:GOARCH
        Write-Host 'Env:CGO_ENABLED =' \$env:CGO_ENABLED
    """
}